---
#Update nginx configuration
- name: nginx-configuration
  hosts: nginx
  become: yes 
  tasks:
    - name: Replace nginx.conf
      copy:
        src: ../nginx-templates/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        force: yes
        mode: 0770
    - name: Create proxy.conf
      copy:
        src: ../nginx-templates/proxy.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        force: yes
        mode: 0770
    - name: Replace fastcgi.conf
      copy:
        src: ../nginx-templates/fastcgi.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        force: yes
        mode: 0770
    - name: Replace mime.types
      copy:
        src: ../nginx-templates/mime.types
        dest: /etc/nginx/nginx.conf
        owner: root
        force: yes
        mode: 0770
    - name: Copy default response
      copy:
        src: ../static-files/index.html
        dest: /etc/nginx/default/default.html
        owner: root
        force: yes
        mode: 0770
    - name: Run nginx config tests
      command: nginx -t
    - name: restart nginx
      service:
        name: nginx
        state: restarted